name: 79475_devchallenge_21

services:
  postgres:
    image: postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "celery -A apiproject worker -l INFO"
    depends_on:
      - rabbitmq
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    command: >
      bash -c "python manage.py migrate && python manage.py loaddata seed-data.json && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    volumes:
      - ./apiproject/:/usr/src/app/
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - postgres
      - celery
    env_file:
      - .env

volumes:
  pgdbdata: null
