# Generated by Django 5.1.1 on 2024-09-29 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True)),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('location', models.CharField(null=True)),
                ('emotional_tone', models.IntegerField(choices=[(0, 'Neutral'), (1, 'Positive'), (2, 'Negative'), (3, 'Angry')], null=True)),
                ('text', models.CharField(null=True)),
                ('task_id', models.CharField(null=True)),
                ('categories', models.ManyToManyField(related_name='calls', to='apiapp.category')),
            ],
        ),
    ]
