# Generated by Django 5.1.1 on 2024-09-24 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('location', models.CharField()),
                ('emotional_tone', models.CharField(choices=[('NEU', 'Neutral'), ('POS', 'Positive'), ('NEG', 'Negative'), ('ANG', 'Angry')], default='NEU', max_length=3)),
                ('text', models.CharField()),
                ('categories', models.ManyToManyField(to='apiapp.category')),
            ],
        ),
    ]
